### ISSUE TITLE
Maybe dummy question: why I don't see paquet sent by first hackrf to 127.0.0.1:52001 received by second hackRf on 127.0.0.1:52002?

### ISSUE THREAD

**Issue by cloatre** [AFITWiSec/EZ-Wave#11]
Hello,

I use the script ezstrumbler:

---------------------
root@kali:~/EZ-Wave/tools# python ezstumbler.py -t 20
WARNING: No route found for IPv6 destination :: (no default route?)
Sniffing for 20 seconds...
[+] Found new Zwave network: 0xea41dcac
[+][+] Found new Zwave node: 0xea41dcac node 1
[+][+] Found new Zwave node: 0xea41dcac node 2
Active Scan of 0xea41dcac for 20 seconds...

****************** Scan Results *********************

*************** Home ID: 0xea41dcac *****************
	NodeID 1
	NodeID 2

*****************************************************

*****************************************************

------------------

So when activeScan is made, I see in wireshark a lot of paquet sent to 127.0.0.1:52001
-->If everything is ok, it is sent to the transmit hackRf.

Should it be received also by second hackRF (that will send to 127.0.0.1:52002) ?

Why i don't see these paquets in wireshark? 

Thanks,

[EDIT]
I change the file top_block in order to replace "hackrf=0/1" by my id of hackRf and it is better, I see Zwave paquet comming now.
radio/Zwave/top_block.py:        self.osmosdr_source_0 = osmosdr.source( args="numchan=" + str(1) + " " + "hackrf=2f3b23e1" )
radio/Zwave/top_block.py:        self.osmosdr_sink_0 = osmosdr.sink( args="numchan=" + str(1) + " " + "hackrf=2f4375e1" )

**Comment by gitjhall** [comment]
@cloatre  The packet being sent to port 50001 only signifies the packet being sent from scapy to gnuradio. It does not mean the packet is actually making it through the flowgraph and to the hackrf for transmission thus there is no packet for your receiver to pick up. When your transmitter is working properly your receiver will see what is being transmitted (though not with 100% accuracy due to timing and interference). 

This means that the packets in wireshark on port 50001 != the packets actually being transmitted. This is true even when everything is working properly because the hackrf does some buffering that sometimes ends up transmitting partial packets (which get dropped by the target device and won't be seen by your receiver). E.g. you may have a script that sends 10 packets, you'll see 10 packets in wireshark on port 50001 but the hackrf may only transmit 6 valid packets. So if you're using ez-wave to mess around with z-wave devices this won't really matter to you because you can always just send more packets, but if you're trying to do academic research this makes data collection and statistics very difficult without a 3rd SDR on a separate machine sniffing constantly to valid what is being transmitted.

**Comment by cloatre** [comment]
Ok thanks .
