### ISSUE TITLE
Try to modify ezrecon.py to send paquet to switch on/off a fibaro wall plug

### ISSUE THREAD

**Issue by cloatre** [AFITWiSec/EZ-Wave#12]
Hello,

Is-it the right way to modify the main function like this?

--------------------------

...
    nif = ZWave(homeid=homeid, dst=nodeid) / ZWaveNodeInfo() / chr(2)
    print "add command to switch plug"
    allume=ZWave(homeid=homeid, dst=nodeid) / ZWaveSwitchBin(cmd="SET")
...

while time.time() - timer < timeout:
          for _ in range(0,3):
                send(allume, verbose=True)

-------------------------

It does not work, when I compare paquets in wireshark I see the data transmitted is 0x25 01 0e
(In a previous post I have seen that the command to switch off is 0x25 01 00 )
Maybe there are some other parameter to configure...

Thanks,

**Comment by gitjhall** [comment]
1. Personally I wouldn't modify ezrecon.py because it's doing a lot more than what's needed to simply turn a device on/off. It's transmitting specific packets and waiting for specific responses. If all you want to do it turn on/off a device, it's a lot easier to just write a new script. Below what I would do...but I wrote this just now in the browser so there could be some indention errors or typos and I no longer have hackrfs to test this out on...so YMMV:

2. Notice in the script below where I build each packet (the ON and OFF packets)? That's building a Z-Wave packet using Scapy. Those packets (and most z-wave packets) are made up of 3 scapy layers: ZWave, a command class layer, and raw data layer. You can see the definition of the Z-Wave and command class layers [here](https://github.com/AFITWiSec/EZ-Wave/blob/master/setup/scapy/layers/ZWave.py). The command class layer includes the command class and a command. The data layer lets you can put any value in, but you'll need an understanding of the z-wave protocol and the target device in order to know what to put in this layer.
In your post you defined the packet as:
`allume=ZWave(homeid=homeid, dst=nodeid) / ZWaveSwitchBin(cmd="SET")`
Notice you have no data layer. And what you saw in wireshark included 0x25 01 0e. The first two bytes are the command class layer (in this case x25 for ZWaveSwitchBin and x01 for SET). I'm willing to bet the 3rd byte you see is the checksum for the whole packet. So basically, you told the device to set, but you didn't tell it what to set to. Most Z-Wave devices that support the binary switch command class accept x00 as OFF and xFF or x63 (decimal 99) as ON.

`#!/usr/bin/python

import os
from scapy.modules.gnuradio import *
from scapy.all import *
from scapy.layers.ZWave import *
from utils.ezutils import *
from argparse import ArgumentParser

if __name__ == "__main__":
    parser = ArgumentParser(sys.argv[0])
    parser.add_argument("homeid", type=str, help="4 byte HomeID of target network (ex: 0x1a2b3c4d)")
    parser.add_argument("nodeid", type=int, help="Target device NodeID (in decimal, <233)" )
    parser.add_argument("-t", "--timeout", type=int, default=30, help="Stop toggling after a given time (secs, default=30)")

    args = parser.parse_args(sys.argv[1:])
    load_module('gnuradio')
    homeid = int(args.homeid,16)
    nodeid = args.nodeid
    print "Toggling " + hex(homeid) + " Node " + str(nodeid)
    timeout = args.timeout
    timer = time.time()
        toggle = 0
        while time.time() - timer < timeout:
            toggle = (toggle + 1)  % 2
            if toggle:
                #OFF
                packet = ZWave(homeid=homeid, dst=nodeid) / ZWaveSwitchBin(cmd="SET") / chr(0) #or \x00
            else:
                #ON
                packet = ZWave(homeid=homeid, dst=nodeid) / ZWaveSwitchBin(cmd="SET") / chr(255) #or \xFF
            #send the packet 3 times to make sure it actually gets sent
            for _ in range(0,3):
                send(packet)
            time.sleep(2)
    #print "Exit"`

**Comment by cloatre** [comment]
Hello,

Thanks for help, for my device I just have to chenge chr(255) by chr(99)

I have compared pakets sent on my wireshark:
on the bottom, this is the paket to switch OFF that I have captured with my HackRf
on the top, this is the packet that I send threw my HackRf (the one from upper script)

The only differences are the UDP source port and the CRC.

-->so I think the script should work to toogle my wall plug, but it doesn't...what have I missed?

![screenshot from 2016-07-28 10 15 37](https://cloud.githubusercontent.com/assets/20278605/17207536/f450b878-54ac-11e6-97ff-05cb4a791e4c.png)

**Comment by gitjhall** [comment]
@cloatre There's one other difference between the packets you missed and it's the reason the checksums are different. If you expand the Z-Wave layer in wireshark, you'll see the destination id in the packet from the bottom picture is 2 (your wall plug). This packet works. But the destination id in the packet from the top picture is 1 (your controller). This packet won't do anything because your controller is clearly not a binary switch. So make sure you're setting the destination id to the node you want to target.

**Comment by cloatre** [comment]
@gitjhall  
I had uploaded the wrong screenshot, I update to the good one: destination and source are the same now in both packet.

**Comment by cwbadenhop** [comment]
Perhaps the transmit gain on the TX hackrf is too low?

**Comment by cloatre** [comment]
I think my problem is about transmitting packet: I don't see anything on waterfall view at the 868,4Mhz of gnuradio-companion.
1) I record the switch ON/OFF traffic seen by the hackrf on my first laptop
2) I try to replay this record on my second laptop
3) I do not see anything on the first laptop that is recording

**Comment by cloatre** [comment]
You will kill me: I wrote a wrong home id
-->
I wrote:
0xeb41dcac
instead of 
0xea41dcac


Below I share my ezrecon script that I have adapted in order to toogle my wall plug :-)
(I don't know why but I need to call the function "sniffradio" line 98 before my first packet are sent, if not it does not work)

Like pharell williams says: I'm so happy!!! 

------------------------------------

#!/usr/bin/python

#this script is ezrecon.py that has been modified in order to toogle a wall plug (like fibaro)
#to use it, you need first to detect Zwave Network with ezstumbler.py passive scan

import os
from scapy.modules.gnuradio import *
from scapy.all import *
from scapy.layers.ZWave import *
from utils.ezutils import *
from argparse import ArgumentParser


def verify_checksum(packet):
    p = bytearray(str(packet))
    p = p[:-1]
    calc_crc = hex(reduce(lambda x, y: x ^ y, p, 0xFF))
    crc_byte = packet[ZWaveReq].get_field('crc').i2repr(packet, packet.crc)
    if calc_crc == crc_byte:
        return True
    else:
        return False


def handle_packets(packet, target):
    if packet.homeid == target.homeid and packet.src == target.nodeid:
        if verify_checksum(packet[ZWaveReq]):
            #packet[ZWaveReq].show()
            if packet.cmd_class == 0x72 and packet.cmd == 0x05:
                target.manspec = str(packet[Raw]).encode("HEX")
                target.parse_manspec()
                return
            elif packet.cmd_class == 0x86 and packet.cmd == 0x12:
                target.version = str(packet[Raw]).encode("HEX")
                return
            elif packet.cmd_class == 0x01:
                target.cmdclasses = str(packet[Raw])[6:].encode("HEX")
                return
            elif packet.cmd_class == 0x20 and packet.cmd == 0x03:
                target.basic = str(packet[Raw]).encode("HEX")
                return
            elif packet.cmd_class == 0x70 and packet.cmd == 0x06:
                target.configs[str(packet[Raw])[:2].encode("HEX")] = str(packet[Raw])[2:].encode("HEX")


if __name__ == "__main__":
    parser = ArgumentParser(sys.argv[0])
    parser.add_argument("homeid", type=str, help="4 byte HomeID of target network (ex: 0x1a2b3c4d)")
    parser.add_argument("nodeid", type=int, help="Target device NodeID (in decimal, <233)" )
    parser.add_argument("-c", "--config", action="store_true",
                        help="Include scan of device configuration settings (takes a while)")
    parser.add_argument("-t", "--timeout", type=int, default=30,
                        help="Stop scanning after a given time (secs, default=30)")

    args = parser.parse_args(sys.argv[1:])

    load_module('gnuradio')

    homeid = int(args.homeid,16)
    nodeid = args.nodeid
    _target = ZWaveNode(homeid, nodeid)

    print "Interrogating " + hex(homeid) + " Node " + str(nodeid)

    if args.config:
        config = ZWave(homeid=homeid, ackreq=1, dst=nodeid) / ZWaveConfiguration(cmd="GET")
        _target.configs = dict()
    else:
        _target.configs = False

    timeout = args.timeout
    #add lcl
    print "debut toogle"
    timer = time.time()
    toggle = 0
    
    #fin add lcl
    pid = os.fork()
    if pid > 0:
        timer = time.time()
        i = 0
        while time.time() - timer < timeout:
            toggle = (toggle + 1)  % 2
            print "send command 3 times"
            if toggle:
                #OFF
                print "send OFF"
                packet = ZWave(homeid=homeid, dst=nodeid) / ZWaveSwitchBin(cmd="SET") / chr(0) #or \x00 for OFF
            else:
                #ON
                print "send ON"
                packet = ZWave(homeid=homeid, dst=nodeid) / ZWaveSwitchBin(cmd="SET") / chr(99) #or \x63 for ON
            #send the packet 3 times to make sure it actually gets sent
            for _ in range(0,3):
                send(packet, verbose=True)
                time.sleep(1)
            time.sleep(3)

    else:
        #need to keep this function, toogle does not work if not kept
        sniffradio(radio="Zwave", store=0, count=None, timeout=timeout,
                   prn=lambda p,t=_target: handle_packets(p,t),
                   lfilter=lambda x: x.haslayer(ZWaveReq))

        print "\n****************** Recon Results *********************\n"
        print "**************** Home ID: " + hex(homeid) + " *****************"
        #_target.display(verbose=True)


    print "Exit"


-----------------------------------
