### ISSUE TITLE
Problem with Scapy layers

### ISSUE THREAD

**Issue by cloatre** [AFITWiSec/EZ-Wave#14]
Hello,

I am trying to run experiment with last version of Kali.
I have some problems.

First, because of the error:

`root@kali:~/EZ-Wave/tools# python ezstumbler.py 
WARNING: No route found for IPv6 destination :: (no default route?)
ERROR: No module named scanner_802_15_4
Traceback (most recent call last):
  File "ezstumbler.py", line 4, in <module>
    from utils.ezutils import *
  File "/root/EZ-Wave/tools/utils/ezutils.py", line 3, in <module>
    from scapy.modules.gnuradio import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/modules/gnuradio.py", line 20, in <module>
    import scapy.layers.gnuradio
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/gnuradio.py", line 38, in <module>
    bind_layers(GnuradioPacket, WMBus, proto=4)
NameError: name 'WMBus' is not defined
` 
I had to change "class WMBus(Packet)" by "class WMBusLinkLayer(Packet)" in the file EZ-Wave/setup/scapy/layers/gnuradio.py

I have no problem to run demodulation with the zwave.grc in gnuradio-companion.

But the script ezstumbler.py still does not work, maybe because of "ERROR: No module named scanner_802_15_4".

I also have to build hackrf before gr-osmocom.

I use:
`root@kali:~/EZ-Wave/tools# uname -a
Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

root@kali:~/EZ-Wave/tools# pybombs --version
2.2.0

`

**Comment by gitjhall** [comment]
@cloatre It looks like the [scapy-radio](https://bitbucket.org/cybertools/scapy-radio) devs made some changes recently that affect the gnuradio layer in scapy, specifically how the gnuradio layer binds to the WMBus layer (which is completely unrelated to Z-Wave or the purpose of EZ-Wave)...This has an effect on EZ-Wave/setup/layers/gnuradio.py because I left in support for protocols other than Z-Wave (I should have just removed them from the start).

I recommend commenting out or deleting lines 12-14 and 32-38 in EZ-Wave/setup/layers/gnuradio.py removing all supported protocols other than Z-Wave. Then run the scapy_update function of the EZ-Wave setup script (sudo EZ-Wave/.setup.sh scapy_update) to update the installed scapy layers and modules with the edited versions in EZ-Wave/setup/scapy/.

Of course I can't test any of this because I'm no longer using HackRFs and GNU Radio so let me know if it works and I'll update the master.

**Comment by cloatre** [comment]
Ok it works.

thanks

**Comment by gitjhall** [comment]
Master updated
